version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule: { interval: daily }
    versioning-strategy: increase
    allow: [dependency-type: direct]
    assignees: [MorevM]
    commit-message: { prefix: chore }
    labels: [dependencies]
